FROM alpine:latest


RUN		apk update && \
		apk add --no-cache nginx

RUN		mkdir -p /run/nginx

COPY	./*.html				/var/www/html/
COPY	./conf/nginx.conf		/etc/nginx/nginx.conf

EXPOSE 443

ENTRYPOINT ["nginx", "-g", "daemon off;"]
