FROM alpine:latest


RUN		apk update && apk add --no-cache \
		nginx \
		openssl \
		sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
		-subj "/C=DE/ST=NS/O=42WOB/CN=dfranke.42.fr" \
		-out /etc/ssl/certs/dfranke.crt \
		-keyout /etc/ssl/private/dfranke.key

RUN		mkdir -p /run/nginx

COPY	./*.html				/var/www/html/
COPY	./conf/nginx.conf		/etc/nginx/nginx.conf

EXPOSE 443

ENTRYPOINT ["nginx", "-g", "daemon off;"]
