FROM alpine:latest

RUN     apk update && apk add --no-cache \
        mariadb \
        mariadb-client && \
        openrc \
        mkdir /run/mysqld && \
        chown mysql:mysql /run/mysqld && \
        rm -rf /var/cache/apk/*

CMD     [ "mysqld", "--user=mysql", "--console"]