FROM alpine:latest

RUN     apk update && apk add --no-cache \
        mariadb \
        mariadb-client \
        bash

RUN	mkdir -p /var/lib/mysql /var/run/mysqld; \
        chown -R mysql:mysql /var/lib/mysql /var/run/mysqld; \
        chmod +x /var/run/mysqld;

COPY    ./conf/my.cnf           /etc/
COPY    ./tools/create_db.sh    /usr/bin/

EXPOSE 3306

ENTRYPOINT [ "sh", "/usr/bin/create_db.sh"]

CMD     [ "mariadbd" ]
